default: true
MD003: false        # Heading style
MD013:              # Line length
  line_length: 300
MD022: false        # Headings should be surrounded by blank lines
MD024: false        # Multiple headings with the same content
MD025: false        # Multiple top-level headings in the same document
MD033: false        # Inline HTML
MD034: false        # Bare URL used
MD053: false        # Link and image reference definitions should be needed
