site_name: DevPro Presentations
nav:
  - Home: index.md
  - About: about.md
theme:
  # other
  name: dracula  # mkdocs, materialtheme, dracula
  locale: en
  # color_mode: auto
  # user_color_mode_toggle: true
  # static_templates:
  #   - sitemap.html
# extra_css:
#   - css/extra.css
# theme: readthedocs
