# purpose: continuously deploy the presentations
# actions:
#   - https://github.com/marketplace/actions/checkout
#   - https://github.com/actions/setup-node
# images:
#   - https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Instal Node.js (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: Install Slidev packages
        working-directory: slidev
        run: npm install
      - name: Lint code
        run: task lint
      - name: Build web content
        run: |
          task marp:build
          task marp:publish
          task slidev:publish
