name: Deploy                                          # Continuously Deployment

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  SITE_BASE: presentations

jobs:
  deploy:
    runs-on: ubuntu-latest                          # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4                   # https://github.com/marketplace/actions/checkout
      - name: Instal Node.js (LTS)
        uses: actions/setup-node@v4                 # https://github.com/actions/setup-node
        with:
          node-version: 'lts/*'
      - name: Install Task (taskfile.dev)
        uses: arduino/setup-task@v2                 # https://github.com/arduino/setup-task
      - name: Install Slidev packages
        working-directory: slidev
        run: npm install
      - name: Build web content
        run: |
          task marp:build
          task marp:publish
          task slidev:publish
      - name: Setup Pages
        uses: actions/configure-pages@v4            # https://github.com/actions/configure-pages
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3      # https://github.com/actions/upload-pages-artifact
        with:
          path: dist
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4               # https://github.com/actions/deploy-pages
